const code=String.raw`
(()=>{
 const JP='https://fujgwahltvbigyftpfjz.supabase.co/functions/v1/warehouse-jsonp';
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fa=n=>Number(n||0).toLocaleString('fa-IR');
 let user=null,records=[];
 const css='.v9-stage-box{margin-top:10px;padding:10px 12px;border:1px solid var(--vx-line,var(--line));border-radius:13px;background:var(--vx-soft,var(--card-2))}.v9-stage-row{display:grid;grid-template-columns:160px 1fr;gap:8px;align-items:end}.v9-hint{font-size:11px;color:var(--vx-muted,var(--muted));min-height:20px;padding:2px 2px 0}.v9-hint.exists{color:var(--vx-p,var(--primary));font-weight:800}.v9-doc{margin-top:10px;padding-top:10px;border-top:1px solid var(--vx-line,var(--line))}.v9-doc label{font-size:11px}.v9-doc-row{display:grid;grid-template-columns:1fr auto;gap:7px;align-items:center}.v9-doc-row input{min-height:42px!important}.v9-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.v9-actions button{width:auto!important;min-width:104px!important;min-height:42px!important;padding:8px 12px!important}.v9-delete{background:color-mix(in srgb,var(--vx-danger,var(--danger)) 10%,var(--vx-card,var(--card)))!important;color:var(--vx-danger,var(--danger))!important;border-color:color-mix(in srgb,var(--vx-danger,var(--danger)) 30%,var(--vx-line,var(--line)))!important}.v9-save-note{background:var(--vx-soft,var(--card-2))!important;color:var(--vx-p,var(--primary))!important;border-color:var(--vx-line,var(--line))!important}@media(max-width:600px){.v9-stage-row,.v9-doc-row{grid-template-columns:1fr}.v9-actions button{flex:1;min-width:0!important}}';
 let st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
 function call(action,data={},auth=true){return new Promise((resolve,reject)=>{const token=localStorage.getItem('warehouse_token')||'',cb='v9'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const clean=()=>{if(done)return;done=true;try{delete window[cb]}catch{}s.remove()};window[cb]=j=>{clean();Number(j?.__status)>=400?reject(Object.assign(new Error(j.error||'خطا'),{data:j})):resolve(j)};s.onerror=()=>{clean();reject(new Error('ارتباط با سرور برقرار نشد'))};const p=new URLSearchParams({cb,action,payload:JSON.stringify(data)});if(auth&&token)p.set('token',token);s.src=JP+'?'+p.toString();document.body.appendChild(s);setTimeout(()=>{if(!done){clean();reject(new Error('پاسخ سرور دیر رسید'))}},16000)})}
 function notify(t){const m=$('message');if(m){m.innerHTML='<div class="msg">'+esc(t)+'</div>';setTimeout(()=>m.innerHTML='',4500)}else alert(t)}
 function ensureStageUI(){const inv=$('invoiceNo'),cus=$('customer');if(!inv||!cus||$('stageNo'))return;const box=document.createElement('div');box.className='v9-stage-box';box.innerHTML='<div class="v9-stage-row"><div><label for="stageNo">مرحله بارگیری</label><select id="stageNo">'+Array.from({length:15},(_,i)=>'<option value="'+(i+1)+'">مرحله '+fa(i+1)+'</option>').join('')+'</select></div><div><div id="invoiceHint" class="v9-hint">برای فاکتور جدید، مرحله ۱ ثبت می‌شود.</div></div></div>';const host=cus.closest('.input-grid')||cus.parentElement;host.after(box);let timer;const check=()=>{clearTimeout(timer);timer=setTimeout(checkInvoice,260)};inv.addEventListener('input',check);inv.addEventListener('blur',checkInvoice)}
 async function checkInvoice(){const inv=$('invoiceNo'),cus=$('customer'),stage=$('stageNo'),hint=$('invoiceHint');if(!inv||!stage)return;const no=inv.value.trim();if(!no){stage.value='1';if(cus)cus.readOnly=false;if(hint){hint.className='v9-hint';hint.textContent='برای فاکتور جدید، مرحله ۱ ثبت می‌شود.'}return}try{const x=await call('invoice_info',{invoice_no:no});if(x.exists){stage.value=String(x.next_stage);if(cus){cus.value=x.customer_name||cus.value;cus.readOnly=true}if(hint){hint.className='v9-hint exists';hint.textContent='این فاکتور قبلاً تا مرحله '+fa(x.last_stage)+' ثبت شده است — بارگیری جدید باید مرحله '+fa(x.next_stage)+' باشد.'}}else{stage.value='1';if(cus)cus.readOnly=false;if(hint){hint.className='v9-hint';hint.textContent='فاکتور جدید — ثبت به‌عنوان مرحله ۱.'}}}catch(e){if(hint)hint.textContent=e.message}}
 function workersPayload(){return [...document.querySelectorAll('.worker-line')].map(r=>({worker_id:r.querySelector('.wsel')?.value||'',amount:Number((r.querySelector('.wamt')?.value||'0').replace(/,/g,''))})).filter(x=>x.worker_id&&x.amount>0)}
 async function register(e){e.preventDefault();e.stopImmediatePropagation();const btn=$('registerBtn');if(!btn)return;try{btn.disabled=true;const ws=workersPayload(),stageNo=Number($('stageNo')?.value||1);const j=await call('register_stage',{invoice_no:$('invoiceNo')?.value.trim()||'',customer_name:$('customer')?.value.trim()||'',stage_no:stageNo,workers:ws,notes:$('notes')?.value.trim()||''});notify('مرحله '+fa(j.stage_no)+' با موفقیت ثبت شد');$('invoiceNo').value='';$('customer').value='';$('customer').readOnly=false;if($('notes'))$('notes').value='';if($('stageNo'))$('stageNo').value='1';if($('invoiceHint')){$('invoiceHint').className='v9-hint';$('invoiceHint').textContent='برای فاکتور جدید، مرحله ۱ ثبت می‌شود.'}document.querySelectorAll('.wamt').forEach(x=>x.value='');await refresh()}catch(err){if(err.data?.expected_stage&&$('stageNo'))$('stageNo').value=String(err.data.expected_stage);notify(err.message||'ثبت انجام نشد')}finally{btn.disabled=false}}
 function card(x){const inv=x.invoice?.invoice_no||'',customer=x.invoice?.customer_name||'',settled=!!x.settled_at,note=x.settlement_note||'',loadingNote=x.notes||'',manager=user?.role==='manager';return '<div class="stage" data-stage-id="'+x.id+'"><div class="stage-top"><div style="flex:1"><h4>فاکتور '+esc(inv)+' — '+esc(customer)+'</h4><div class="meta">مرحله '+fa(x.stage_no)+' · '+new Date(x.created_at).toLocaleString('fa-IR')+'</div><div class="amount">'+fa(x.amount_total)+' تومان</div><div class="tags">'+(settled?'<span class="tag badge ok">تسویه شده</span>':'<span class="tag badge">تسویه نشده</span>')+(x.creator?.display_name?'<span class="tag badge">ثبت: '+esc(x.creator.display_name)+'</span>':'')+'</div>'+(loadingNote?'<div class="subtle" style="margin-top:7px">یادداشت بارگیری: '+esc(loadingNote)+'</div>':'')+(manager?'<div class="v9-doc"><label>یادداشت سند / تسویه</label><div class="v9-doc-row"><input class="field v9-note" maxlength="500" value="'+esc(note)+'" placeholder="شماره سند، توضیح پرداخت یا یادداشت"><button class="v9-save-note" type="button">ذخیره یادداشت</button></div><div class="v9-actions">'+(!settled?'<button class="v9-settle" type="button">✓ تسویه شد</button>':'')+'<button class="v9-delete" type="button">حذف</button></div></div>':(note?'<div class="subtle" style="margin-top:7px">یادداشت سند: '+esc(note)+'</div>':''))+'</div></div></div>'}
 function bindCards(){document.querySelectorAll('#stages .stage').forEach(el=>{const id=el.dataset.stageId,note=el.querySelector('.v9-note');el.querySelector('.v9-save-note')?.addEventListener('click',async()=>{try{await call('save_settlement_note',{stage_id:id,note:note?.value||''});notify('یادداشت سند ذخیره شد')}catch(e){notify(e.message)}});el.querySelector('.v9-settle')?.addEventListener('click',async()=>{if(!confirm('این مرحله به‌عنوان «تسویه شده» ثبت شود؟'))return;try{await call('settle_stage',{stage_id:id,note:note?.value||''});notify('تسویه با موفقیت ثبت شد');await refresh()}catch(e){notify(e.message)}});el.querySelector('.v9-delete')?.addEventListener('click',async()=>{if(!confirm('این مرحله از سوابق حذف شود؟ این کار برای حذف ثبت تکراری است.'))return;try{await call('delete_stage',{stage_id:id});notify('ثبت حذف شد');await refresh()}catch(e){notify(e.message)}})})}
 async function refresh(){try{const j=await call('dashboard');records=j.stages||[];if($('sTotal'))$('sTotal').textContent=fa(j.summary.total)+' تومان';if($('sSettled'))$('sSettled').textContent=fa(j.summary.settled)+' تومان';if($('sUnsettled'))$('sUnsettled').textContent=fa(j.summary.unsettled)+' تومان';if($('stages'))$('stages').innerHTML=records.length?records.map(card).join(''):'<div class="empty">هنوز ثبتی وجود ندارد.</div>';bindCards()}catch(e){notify(e.message||'خطا در دریافت سوابق')}}
 function csv(e){e.preventDefault();e.stopImmediatePropagation();const rows=[['فاکتور','مشتری','مرحله','مبلغ','وضعیت','یادداشت سند'],...records.map(x=>[x.invoice?.invoice_no||'',x.invoice?.customer_name||'',x.stage_no,x.amount_total,x.settled_at?'تسویه شده':'تسویه نشده',x.settlement_note||''])],out='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'text/csv'}));a.download='گزارش-بارگیری.csv';a.click()}
 function boot(){ensureStageUI();const reg=$('registerBtn');if(reg&&!reg.dataset.v9){reg.dataset.v9='1';reg.addEventListener('click',register,true)}const ref=$('refreshBtn');if(ref&&!ref.dataset.v9){ref.dataset.v9='1';ref.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();refresh()},true)}const c=$('csvBtn');if(c&&!c.dataset.v9){c.dataset.v9='1';c.addEventListener('click',csv,true)}const token=localStorage.getItem('warehouse_token');if(token&&!user){call('me').then(x=>{user=x.user;refresh()}).catch(()=>{})}setTimeout(boot,900)}
 boot();
})();`;
Deno.serve(()=>new Response(code,{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}}));
