const code=String.raw`
(()=>{
const JP='https://fujgwahltvbigyftpfjz.supabase.co/functions/v1/warehouse-jsonp';
document.documentElement.lang='fa';document.documentElement.dir='rtl';
const css='*{box-sizing:border-box}body{margin:0;background:#f5f7fa;color:#17212b;font-family:Tahoma,Arial,sans-serif}.top{background:#173b57;color:#fff;padding:15px}.wrap{max-width:880px;margin:auto;padding:12px}.card{background:#fff;border:1px solid #dfe7ec;border-radius:14px;padding:14px;margin-bottom:12px}.row{display:flex;gap:8px;flex-wrap:wrap}.row>*{flex:1;min-width:135px}input,select,textarea,button{font:inherit;width:100%;padding:12px;border:1px solid #ccd8df;border-radius:10px;background:#fff}button{background:#173b57;color:#fff;border:0;font-weight:bold}.secondary{background:#edf3f6;color:#173b57}.danger{background:#a63a3a}.hide{display:none!important}.muted{font-size:12px;color:#71808a}.sum{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.sum div{background:#f4f7f9;border-radius:10px;padding:10px;text-align:center}.num{font-size:17px;font-weight:bold}.workerLine{display:grid;grid-template-columns:1fr 125px 40px;gap:6px;margin:6px 0}.stage{border-top:1px solid #edf1f3;padding:10px 0}.stage:first-child{border-top:0}.msg{background:#fff4d6;color:#735313;padding:10px;border-radius:10px;margin-bottom:10px}.badge{padding:3px 8px;border-radius:999px;background:#fff0e5;color:#9a4e12;font-size:11px}.badge.ok{background:#e7f6ed;color:#18703c}.pinbox{max-width:320px;margin:0 auto}.pinbox input{text-align:center;font-size:24px;letter-spacing:8px}.pinbox button{margin-top:10px}@media(max-width:600px){.sum{grid-template-columns:1fr}.workerLine{grid-template-columns:1fr 100px 38px}.wrap{padding:8px}}';
let st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
document.body.innerHTML='<div class="top"><div class="wrap" style="padding:0"><h3 style="margin:0">مدیریت بارگیری و دستمزد</h3></div></div><div class="wrap"><div id="message"></div><div id="login" class="card"><h3 style="text-align:center">ورود با PIN</h3><div class="pinbox"><input id="loginPin" type="password" inputmode="numeric" maxlength="4" placeholder="••••"><button id="loginBtn">ورود</button></div><div class="muted" style="margin-top:10px;text-align:center">فقط PIN چهار رقمی را وارد کنید؛ نام کاربری لازم نیست.</div></div><div id="app" class="hide"><div class="card"><div class="row"><div><b id="who"></b><div id="role" class="muted"></div></div><button id="logoutBtn" class="secondary">خروج</button></div></div><div class="card"><div class="sum"><div>جمع کل<div id="sTotal" class="num">۰</div></div><div>تسویه‌شده<div id="sSettled" class="num">۰</div></div><div>مانده<div id="sUnsettled" class="num">۰</div></div></div></div><div class="card"><h3>ثبت بارگیری</h3><div class="row"><input id="invoiceNo" placeholder="شماره فاکتور"><input id="customer" placeholder="نام صاحب فاکتور"></div><div id="workerRows"></div><button id="addWorkerBtn" class="secondary">+ افزودن کارگر</button><textarea id="notes" placeholder="توضیحات (اختیاری)" style="margin-top:8px"></textarea><button id="registerBtn" style="margin-top:8px">ثبت مرحله بارگیری</button><button id="archiveBtn" class="secondary" style="margin-top:8px">بایگانی برگه جاری</button></div><div id="managerTools" class="card hide"><h3>مدیریت کارگرها</h3><div class="row"><input id="newWorker" placeholder="نام کارگر"><input id="newPin" type="password" inputmode="numeric" maxlength="4" placeholder="PIN چهار رقمی"></div><button id="createWorkerBtn" style="margin-top:8px">ساخت حساب کارگر</button></div><div class="card"><div class="row"><h3 style="flex:2">آخرین ثبت‌ها</h3><button id="refreshBtn" class="secondary">به‌روزرسانی</button><button id="csvBtn" class="secondary">Excel/CSV</button><button id="printBtn" class="secondary">چاپ / PDF</button></div><div id="stages"></div></div><div class="card"><h3>تغییر PIN من</h3><div class="row"><input id="newMyPin" type="password" inputmode="numeric" maxlength="4" placeholder="PIN جدید چهار رقمی"><button id="changePinBtn">تغییر PIN</button></div></div></div></div>';
const $=x=>document.getElementById(x),fa=n=>Number(n||0).toLocaleString('fa-IR'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let token=localStorage.getItem('warehouse_token')||'',me=null,workers=[],last=[];
function msg(t){$('message').innerHTML='<div class="msg">'+esc(t)+'</div>';setTimeout(()=>$('message').innerHTML='',3500)}
function call(action,data={},auth=true){return new Promise((res,rej)=>{let cb='w'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script'),done=0;const clean=()=>{if(done)return;done=1;try{delete window[cb]}catch{};s.remove()};window[cb]=j=>{clean();Number(j?.__status)>=400?rej(new Error(j.error||'خطا')):res(j)};s.onerror=()=>{clean();rej(new Error('ارتباط با سرور برقرار نشد'))};let p=new URLSearchParams({cb,action,payload:JSON.stringify(data)});if(auth&&token)p.set('token',token);s.src=JP+'?'+p;document.body.appendChild(s);setTimeout(()=>{if(!done){clean();rej(new Error('پاسخ سرور دیر رسید'))}},15000)})}
function show(){$('login').classList.add('hide');$('app').classList.remove('hide');$('who').textContent=me.name;$('role').textContent=me.role==='manager'?'مدیر':'کارگر';$('managerTools').classList.toggle('hide',me.role!=='manager')}
async function loginNow(){try{let pin=$('loginPin').value.trim();if(!/^\d{4}$/.test(pin))throw new Error('PIN چهار رقمی را وارد کنید');let j=await call('login',{pin},false);token=j.token;me=j.user;localStorage.setItem('warehouse_token',token);$('loginPin').value='';show();await init()}catch(e){msg(e.message)}}
async function init(){workers=(await call('list_workers')).workers||[];$('workerRows').innerHTML='';addRow(me.role==='worker'?me.id:'');await refresh()}
function addRow(sel=''){let d=document.createElement('div');d.className='workerLine';d.innerHTML='<select class="wsel">'+workers.filter(w=>w.role==='worker').map(w=>'<option value="'+w.id+'" '+(w.id===sel?'selected':'')+'>'+esc(w.display_name)+'</option>').join('')+'</select><input class="wamt" inputmode="numeric" placeholder="مبلغ تومان"><button class="danger">×</button>';d.querySelector('button').onclick=()=>d.remove();$('workerRows').appendChild(d)}
async function refresh(){try{let j=await call('dashboard');$('sTotal').textContent=fa(j.summary.total)+' تومان';$('sSettled').textContent=fa(j.summary.settled)+' تومان';$('sUnsettled').textContent=fa(j.summary.unsettled)+' تومان';last=j.stages||[];$('stages').innerHTML=last.length?last.map(x=>'<div class="stage"><b>فاکتور '+esc(x.invoice?.invoice_no||'')+'</b> — '+esc(x.invoice?.customer_name||'')+'<div class="muted">مرحله '+x.stage_no+' · '+new Date(x.created_at).toLocaleString('fa-IR')+'</div><div><b>'+fa(x.amount_total)+' تومان</b> · '+(x.settled_at?'<span class="badge ok">تسویه شده</span>':'<span class="badge">تسویه نشده</span>')+(me.role==='manager'&&!x.settled_at?' <button class="settle" data-id="'+x.id+'" style="width:auto;padding:6px 10px">تسویه</button>':'')+'</div></div>').join(''):'<div class="muted">هنوز موردی ثبت نشده است.</div>';document.querySelectorAll('.settle').forEach(b=>b.onclick=async()=>{try{await call('settle_stage',{stage_id:b.dataset.id});msg('تسویه ثبت شد');refresh()}catch(e){msg(e.message)}})}catch(e){msg(e.message)}}
$('loginBtn').onclick=loginNow;$('loginPin').onkeydown=e=>{if(e.key==='Enter')loginNow()};$('logoutBtn').onclick=()=>{localStorage.removeItem('warehouse_token');location.reload()};$('addWorkerBtn').onclick=()=>addRow();$('refreshBtn').onclick=refresh;$('registerBtn').onclick=async()=>{try{let ws=[...document.querySelectorAll('.workerLine')].map(r=>({worker_id:r.querySelector('.wsel').value,amount:Number((r.querySelector('.wamt').value||'0').replace(/,/g,''))})).filter(x=>x.worker_id&&x.amount>0),j=await call('register_stage',{invoice_no:$('invoiceNo').value.trim(),customer_name:$('customer').value.trim(),workers:ws,notes:$('notes').value.trim()});msg('ثبت شد؛ مرحله '+j.stage_no);$('invoiceNo').value=$('customer').value=$('notes').value='';$('workerRows').innerHTML='';addRow(me.role==='worker'?me.id:'');refresh()}catch(e){msg(e.message)}};$('createWorkerBtn').onclick=async()=>{try{await call('create_worker',{name:$('newWorker').value.trim(),pin:$('newPin').value.trim()});msg('کارگر ساخته شد');$('newWorker').value=$('newPin').value='';workers=(await call('list_workers')).workers||[];$('workerRows').innerHTML='';addRow()}catch(e){msg(e.message)}};$('archiveBtn').onclick=async()=>{if(confirm('برگه جاری بایگانی شود؟'))try{await call('archive_sheet');msg('بایگانی شد')}catch(e){msg(e.message)}};$('changePinBtn').onclick=async()=>{try{await call('change_pin',{pin:$('newMyPin').value.trim()});$('newMyPin').value='';msg('PIN تغییر کرد')}catch(e){msg(e.message)}};$('printBtn').onclick=()=>print();$('csvBtn').onclick=()=>{let rows=[['فاکتور','مشتری','مرحله','مبلغ'],...last.map(x=>[x.invoice?.invoice_no||'',x.invoice?.customer_name||'',x.stage_no,x.amount_total])],csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='گزارش-بارگیری.csv';a.click()};
if(token)call('me').then(j=>{me=j.user;show();init()}).catch(()=>localStorage.removeItem('warehouse_token'));
})();`;
Deno.serve(()=>new Response(code,{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}}));
