import mysql from 'npm:mysql2@^3/promise';
import { createClient } from 'npm:@supabase/supabase-js@2';

const adminKey=(()=>{const modern=Deno.env.get('SUPABASE_SECRET_KEYS');if(modern){try{return JSON.parse(modern).default}catch{}}return Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!})();
const sb=createClient(Deno.env.get('SUPABASE_URL')!,adminKey);

const cfg=()=>({host:Deno.env.get('MYSQL_HOST')||'',port:Number(Deno.env.get('MYSQL_PORT')||3306),user:Deno.env.get('MYSQL_USER')||'',password:Deno.env.get('MYSQL_PASSWORD')||'',database:Deno.env.get('MYSQL_DATABASE')||'',ssl:(Deno.env.get('MYSQL_SSL')||'false').toLowerCase()==='true'?{}:undefined,connectTimeout:6000});
const configured=()=>{const c=cfg();return !!(c.host&&c.user&&c.database)};
async function managerFromToken(token:string){if(!token)return null;const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));const tokenHash=[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');const {data:s}=await sb.from('app_sessions').select('user_id,expires_at').eq('token_hash',tokenHash).maybeSingle();if(!s||new Date(s.expires_at).getTime()<Date.now())return null;const {data:u}=await sb.from('app_users').select('id,display_name,role,active').eq('id',s.user_id).maybeSingle();return u?.active&&u.role==='manager'?u:null}
function js(cb:string,obj:any,status=200){const safe=/^[A-Za-z_$][\w$]*$/.test(cb)?cb:'callback';return new Response(`${safe}(${JSON.stringify({...obj,__status:status})});`,{status:200,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}})}
async function open(){return await mysql.createConnection(cfg() as any)}
const schema=[
`CREATE TABLE IF NOT EXISTS app_users (id CHAR(36) PRIMARY KEY, display_name VARCHAR(150) NOT NULL UNIQUE, role VARCHAR(20) NOT NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME(3) NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
`CREATE TABLE IF NOT EXISTS sheets (id CHAR(36) PRIMARY KEY, owner_user_id CHAR(36) NOT NULL, title VARCHAR(255) NULL, status VARCHAR(20) NOT NULL, created_at DATETIME(3) NULL, archived_at DATETIME(3) NULL, INDEX(owner_user_id), INDEX(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
`CREATE TABLE IF NOT EXISTS invoices (id CHAR(36) PRIMARY KEY, invoice_no VARCHAR(120) NOT NULL UNIQUE, customer_name VARCHAR(255) NULL, created_by CHAR(36) NULL, created_at DATETIME(3) NULL, INDEX(created_by)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
`CREATE TABLE IF NOT EXISTS load_stages (id CHAR(36) PRIMARY KEY, invoice_id CHAR(36) NOT NULL, sheet_id CHAR(36) NULL, stage_no INT NOT NULL, amount_total DECIMAL(18,2) NOT NULL DEFAULT 0, notes TEXT NULL, created_by CHAR(36) NULL, created_at DATETIME(3) NULL, settled_at DATETIME(3) NULL, settled_by CHAR(36) NULL, UNIQUE KEY invoice_stage(invoice_id,stage_no), INDEX(sheet_id), INDEX(created_by), INDEX(settled_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
`CREATE TABLE IF NOT EXISTS stage_workers (id CHAR(36) PRIMARY KEY, stage_id CHAR(36) NOT NULL, worker_id CHAR(36) NOT NULL, amount DECIMAL(18,2) NOT NULL DEFAULT 0, UNIQUE KEY stage_worker(stage_id,worker_id), INDEX(worker_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
`CREATE TABLE IF NOT EXISTS audit_logs (id BIGINT PRIMARY KEY, actor_user_id CHAR(36) NULL, action VARCHAR(120) NOT NULL, entity_type VARCHAR(100) NULL, entity_id VARCHAR(120) NULL, details JSON NULL, created_at DATETIME(3) NULL, INDEX(actor_user_id), INDEX(action)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`];
async function initSchema(){const c=await open();try{for(const q of schema)await c.execute(q);return true}finally{await c.end()}}
async function upsertRows(c:any,table:string,rows:any[],cols:string[],pkCols:string[]){if(!rows?.length)return 0;let count=0;for(const r of rows){const vals=cols.map(k=>{const v=r[k];if(v&&typeof v==='object')return JSON.stringify(v);return v??null});const placeholders=cols.map(()=>'?').join(',');const updates=cols.filter(k=>!pkCols.includes(k)).map(k=>`\`${k}\`=VALUES(\`${k}\`)`).join(',');await c.execute(`INSERT INTO \`${table}\` (${cols.map(k=>'`'+k+'`').join(',')}) VALUES (${placeholders}) ON DUPLICATE KEY UPDATE ${updates}`,vals);count++}return count}
async function syncAll(){await initSchema();const c=await open();try{const tables:any[]=[['app_users',['id','display_name','role','active','created_at'],['id']],['sheets',['id','owner_user_id','title','status','created_at','archived_at'],['id']],['invoices',['id','invoice_no','customer_name','created_by','created_at'],['id']],['load_stages',['id','invoice_id','sheet_id','stage_no','amount_total','notes','created_by','created_at','settled_at','settled_by'],['id']],['stage_workers',['id','stage_id','worker_id','amount'],['id']],['audit_logs',['id','actor_user_id','action','entity_type','entity_id','details','created_at'],['id']]];const out:any={};for(const [name,cols,pks] of tables){const {data,error}=await sb.from(name).select(cols.join(','));if(error)throw error;out[name]=await upsertRows(c,name,data||[],cols,pks)}return out}finally{await c.end()}}
Deno.serve(async(req)=>{try{const u=new URL(req.url),cb=u.searchParams.get('cb')||'callback',action=u.searchParams.get('action')||'status',token=u.searchParams.get('token')||'';if(action==='status'){if(!configured())return js(cb,{ok:true,configured:false,connected:false});try{const c=await open();const [rows]:any=await c.query('SELECT VERSION() version');await c.end();return js(cb,{ok:true,configured:true,connected:true,version:rows?.[0]?.version||''})}catch{return js(cb,{ok:true,configured:true,connected:false})}}const manager=await managerFromToken(token);if(!manager)return js(cb,{error:'دسترسی مدیر لازم است'},403);if(!configured())return js(cb,{error:'تنظیمات MySQL روی سرور ثبت نشده است'},400);if(action==='test'){const c=await open();const [rows]:any=await c.query('SELECT VERSION() version, DATABASE() db');await c.end();return js(cb,{ok:true,connected:true,version:rows?.[0]?.version||'',database:rows?.[0]?.db||''})}if(action==='init_schema'){await initSchema();return js(cb,{ok:true,initialized:true})}if(action==='sync'){return js(cb,{ok:true,synced:true,counts:await syncAll()})}return js(cb,{error:'عملیات ناشناخته'},400)}catch(e){console.error(e);const u=new URL(req.url);return js(u.searchParams.get('cb')||'callback',{error:'خطای اتصال MySQL'},500)}});
